variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: node-build
  tags:
    - linux
  script:
    - yarn
    - yarn build
  artifacts:
    paths:
      - dist/


package:dev:
  stage: package
  tags:
    - shell
  script:
    - docker login ${DOCKER_REPO} -u ${DOCKER_REPO_USER} -p ${DOCKER_REPO_PASS}
    - docker build --pull --build-arg DOCKER_REPO=$DOCKER_REPO -t ${DOCKER_REPO}/apps/api_template:dev-build-$CI_PIPELINE_IID .
    - docker push ${DOCKER_REPO}/apps/api_template:dev-build-$CI_PIPELINE_IID
  except:
    - production

package:prod:
  stage: package
  tags:
    - shell
  script:
    - docker login ${DOCKER_REPO} -u ${DOCKER_REPO_USER} -p ${DOCKER_REPO_PASS}
    - docker build --pull --build-arg DOCKER_REPO=$DOCKER_REPO -t ${DOCKER_REPO}/apps/api_template:build-$CI_PIPELINE_IID .
    - docker push ${DOCKER_REPO}/apps/api_template:build-$CI_PIPELINE_IID
  only:
    - production