# This is a basic workflow to help you get started with Actions

name: CI

on: push
jobs:
  build:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Build
      uses: CultureHQ/actions-yarn@master
      with:
        args: build
